import os

# Direct access
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY","YOUR_API_KEY")
MIXTRAL_API_KEY = os.getenv("MIXTRAL_API_KEY",'YOUR_API_KEY')
MIXTRAL_API_URL = os.getenv("MIXTRAL_API_URL","YOUR_API_URL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY","YOUR_API_KEY")
